### ISSUE TITLE
ERD Button not working

### ISSUE THREAD

**Issue by ThomLowry** [xgeek-net/salesforce-devtools#10]
First, awesome tool and thanks for all the hard work.  I was able to generate an ERD when I first started using you tool, but lately the page just shows a spinning icon, and no ERD is created.  Is there an issue?

**Comment by xgeek-net** [comment]
Hi, @ThomLowry , Thanks for your feedback. It works fine for me, so could you provide more information to find out where the issue occurs.
1. Does it work on some object? such as Account or Contact?
2. Does it work on your SFDC org with other admin user and other PC?
3. Does your PC or company have some firewall to block outside network?

**Comment by xgeek-net** [comment]
Feel free to reopen it if you have any question.
