### ISSUE TITLE
The Value of the selection list is incorrect at excel output.

### ISSUE THREAD

**Issue by SA-KI** [xgeek-net/salesforce-devtools#12]
This tool does so much. I always use it. 
I have found a issue. When exporting an object API reference to Excel, if "&" is included in the value of the selection list, it is replaced with "&amp;".

**Comment by SA-KI** [comment]
I'm sorry. There is one fix.
"&" Will be replaced with "&amp;"

**Comment by xgeek-net** [comment]
Hi, @SA-KI 
This issue is fixed at latest version (v3.2.0), upgrade it and try again.
