### ISSUE TITLE
Field API names

### ISSUE THREAD

**Issue by cmeflygtp** [xgeek-net/salesforce-devtools#14]
Am I missing something but, it appears after the new release; exposing the Field level API's seems that hitting the field level functionality is not working anymore. Just wondering.

**Comment by cmeflygtp** [comment]
So, in testing across different environments; I found that the API Name functionality operates as intended in some environments and NOT in others. There MUST be a setting that needs to be done?

**Comment by xgeek-net** [comment]
Hi, @cmeflygtp Which UI are you using? Lightning or Classic?

**Comment by cmeflygtp** [comment]
tried both actually

**Comment by xgeek-net** [comment]
Seems there has a bug when it works on multi-organization, will check it, thank you for issue reporting.
You can try to reinstall it, that may work.

**Comment by rdebaghosh** [comment]
I faced this problem the switched to Classic and it allowed me to create ERD for the objects . And after that I found I was able to see the menu option for api name

**Comment by rdebaghosh** [comment]
I did not reinstall it

**Comment by xgeek-net** [comment]
If you use DevTools on multi-organizations (sandboxs) in Lightning, there is easy to mistake when Active OAuth authorization. This issue can be reproduced in Lighting but works fine on Classic.

**Comment by rpalmer55** [comment]
I exported the API Object Reference and it gives me most of the field information per object, but not all. Is it possible to include the field Description? We use that to note whether the field is manually updated or updated through ETL.

**Comment by xgeek-net** [comment]
Field Description can’t be exported via SFDC api but you can export Help Text, reference here, https://github.com/xgeek-net/salesforce-devtools/issues/9

**Comment by xgeek-net** [comment]
Feel free to reopen it if you have any question.
