### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by harishmuppala** [xgeek-net/salesforce-devtools#15]
After I click on Active button and enter my Salesforce login credentials, processing screen comes up and it stays on this screen. It is never connecting.
It was working fine until last week, not sure why it is not working today. 
Please let me know if you need any further information.

Thanks

![image](https://user-images.githubusercontent.com/32684640/54874671-49e33080-4dc6-11e9-8671-de7aa9bd7566.png)

**Comment by xgeek-net** [comment]
Hi, @harishmuppala 
Thank you for your report. It was a bug caused by Chrome browser recent security policy update, and I'd fixed it. You can use the latest version(v3.2.2) to try again and enjoy it!

**Comment by harishmuppala** [comment]
It Worked, Awesome!

Thank you very much!
