### ISSUE TITLE
Impossible to open app

### ISSUE THREAD

**Issue by jacopovo** [xgeek-net/salesforce-devtools#16]
It is impossible to Open Salesforce DevTools!

**Comment by xgeek-net** [comment]
@jacopovo  Can you share screenshot or something more?

**Comment by M-Beaty** [comment]
I think they might mean the same issue I'm encountering, where it just hangs on the 5 dots loading, infinitely. I am encountering the same issue. I had another extension that had an issue with the recent update of Chrome, could that be causing an issue? Let me know if I can provide any additional info to support.

**Comment by harishmuppala** [comment]
Same problem hangs on the 5 dots. It was working like a couple of weeks back.

**Comment by xgeek-net** [comment]
I'm not sure the below issue I can reproduce in Lightning is that issue you encountered, seems it is a bug and I will fix it ASAP.
<img width="1291" src="https://user-images.githubusercontent.com/5466487/55925920-38b17500-5c4a-11e9-97d6-d9ce89f0db31.png">

**Comment by xgeek-net** [comment]
@jacopovo @M-Beaty @harishmuppala 
Hi, guys, this issue is fixed in latest version(v3.2.5), can you try again?

**Comment by jacopovo** [comment]
Now Works! Thanks!

**Comment by harshal-gajare** [comment]
@xgeek-net was this issue re introduced in v 3.6.0 ?  [Issue-39](https://github.com/xgeek-net/salesforce-devtools/issues/39)
