### ISSUE TITLE
Broken Images in Chrome Extension

### ISSUE THREAD

**Issue by tpaulaskas** [xgeek-net/salesforce-devtools#17]
When using the Chrome extension in the bottom left corner there appears to be 2 'Aw Snap' images on the same row as the 'Githup Issues' button.

![DevTools Extension](https://user-images.githubusercontent.com/38790760/55669320-a9abf380-582a-11e9-9561-394974660f7f.png)

**Comment by xgeek-net** [comment]
Hi, @tpaulaskas , Seems that Facebook and Twitter services are blocked in your network/company.

**Comment by tpaulaskas** [comment]
I can access both Facebook and Twitter from the network I was using. When I
attempt to do a View Frame Source on the two areas and then review the
view-source: from the URL, the Facebook URL loads a 'Like' and 'Share'
button. However, that 'Like' and 'Share' button won't load in the Chrome
extension. And the Twitter URL on it's own doesn't load at all on it's own.

Here are the frame URLs that are not rendering for me:
https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.xgeek.net%2Fsalesforce%2Ftesforce-for-google-chrome%2F&width=163&locale=en_US&layout=button_count&action=like&size=small&show_faces=true&share=true&height=25

https://platform.twitter.com/widgets/tweet_button.c6def25548e9590b13abaa1b3330b811.en.html#dnt=false&id=twitter-widget-0&lang=en&original_referer=https%3A%2F%2Fwww.xgeek.net%2Fsalesforce%2Ftesforce-for-google-chrome%2F&size=m&text=Salesforce%20Dev%20Tools%20for%20Chrome%E2%84%A2&time=1475373774148&type=share&url=https%3A%2F%2Fwww.xgeek.net%2Fsalesforce%2Ftesforce-for-google-chrome%2F&via=dawn8898



*From: *Xiaoan Lin <notifications@github.com>
*Date: *Sat, Apr 6, 2019 at 6:36 PM
*To: *xgeek-net/salesforce-devtools
*Cc: *tpaulaskas, Mention

Hi, @tpaulaskas
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tpaulaskas&d=DwMCaQ&c=vZI7FCk37fZpIpwDI9E_qA&r=VhG93HhokQY9IRrgS-WExG0T7GqQx8lfAestOIuxgjI&m=uLb1p6_vKIMBbViCiQ7Njeu9Y_ko4ZHznWIegm9YuVU&s=oirz0ZV9gyhtOFf3R3I_0i4IVTBY0uJ8UJyQ0DT3aw4&e=>
> , Seems that Facebook and Twitter services are blocked in your
> network/company.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_xgeek-2Dnet_salesforce-2Ddevtools_issues_17-23issuecomment-2D480551162&d=DwMCaQ&c=vZI7FCk37fZpIpwDI9E_qA&r=VhG93HhokQY9IRrgS-WExG0T7GqQx8lfAestOIuxgjI&m=uLb1p6_vKIMBbViCiQ7Njeu9Y_ko4ZHznWIegm9YuVU&s=8JD-pO1lIX8nGsG4jgpIExBv7jOsMbcBUSUb5UUuBcs&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ak-5FmaCcQ6OCdDbdz1u-2DE5DgLhRuerJ8Aks5veUujgaJpZM4cgK3J&d=DwMCaQ&c=vZI7FCk37fZpIpwDI9E_qA&r=VhG93HhokQY9IRrgS-WExG0T7GqQx8lfAestOIuxgjI&m=uLb1p6_vKIMBbViCiQ7Njeu9Y_ko4ZHznWIegm9YuVU&s=6DVqjFwobYE6enBUEXczyZ4UO-4axG-cFPbf3uLdzbM&e=>
> .
>

-- 

Notice to recipient: This e-mail is only meant for the intended recipient 
of the transmission, and may be a confidential communication or a 
communication privileged by law. If you received this e-mail in error, any 
review, use, dissemination, distribution, or copying of this e-mail is 
strictly prohibited. Please notify us immediately of the error by return 
e-mail and please delete this message from your system. Thank you in 
advance for your cooperation.

**Comment by xgeek-net** [comment]
Hi, this issue can't be reproduced on all of my PC devices and networks，please feel free to reopen it if you have any question.
