### ISSUE TITLE
Unavailable in Professional Edition?

### ISSUE THREAD

**Issue by AidaAtTsuzuku** [xgeek-net/salesforce-devtools#18]
When i start your tool in Professional Edition, i can't activate it with the following img.
In Developer Edition, it operates nomally.
![image](https://user-images.githubusercontent.com/49826477/56465187-c6a01380-6433-11e9-9293-284f403ab968.png)

**Comment by xgeek-net** [comment]
Hi, @AidaAtTsuzuku , you can't use DevTools in Professional Edition, because the edition doesn't support API.

**Comment by AidaAtTsuzuku** [comment]
Got it！Thank you for the quick response！
