### ISSUE TITLE
Apex Code Generator includes non Writable fields

### ISSUE THREAD

**Issue by rickylowekumos** [xgeek-net/salesforce-devtools#2]
Great plugin btw. There is a couple of issues with the 'Apex Generator':

1. The code includes non-writable fields such as formula fields. I suggest using the "IsUpdateable" and "isCreateable" field properties.
2. The dates in the apex produced use "Date.valueOf('DD-MM-YYYY'). This should be Date.valueOf('YYYY-MM-DD')

Cheers,
Ricky

**Comment by xgeek-net** [comment]
Hi, @rickylowekumos 
Thank you for using DevTools and your feedback. 
Seems it is a bug and will be fixed in next version.

**Comment by xgeek-net** [comment]
>The code includes non-writable fields such as formula fields. I suggest using the "IsUpdateable" and "isCreateable" field properties.

Hi, @rickylowekumos , this bug is fixed at latest version (v3.0.3) as your suggestion.
Thanks.

**Comment by xgeek-net** [comment]
Feel free to reopen it if you have any question.
