### ISSUE TITLE
重名项获取API名称错误

### ISSUE THREAD

**Issue by dorawlf** [xgeek-net/salesforce-devtools#20]
页面项目拥有相同名称时，获取到的API名不正确。
貌似所有的同名项目都只能获取到与其同名项中的某一个相同的API名。

■Lightning版
![1](https://user-images.githubusercontent.com/6095094/57593898-70c51400-7578-11e9-956d-bbca16c129c8.jpg)
■Classic版
![2](https://user-images.githubusercontent.com/6095094/57594011-f6e15a80-7578-11e9-9731-c8fc7f039569.jpg)

BTW:非常感谢你的工作！

**Comment by xgeek-net** [comment]
Hi, @dorawlf , 这个问题暂时还没有一个很好的技术解决方案，如果找到的话会尽快解决。谢谢你的反馈！

**Comment by xgeek-net** [comment]
Feel free to reopen it if you have any question.
