### ISSUE TITLE
Issues with Apex Generator

### ISSUE THREAD

**Issue by TimCombridge** [xgeek-net/salesforce-devtools#24]
I've noticed that Apex Generator isn't working properly. It shows RecordType as 'undefined' and doesn't seem to pick up a number of other fields (such as CampaignId). 
Is this a known issue? 

Note: This is in a Summer '19 Sandbox.

**Comment by xgeek-net** [comment]
Hi, @TimCombridge 
Thank you for your report, RecordType in Apex Generator is a known issue (#7 ) needs to be fixed.
