### ISSUE TITLE
Query results are not Exporting

### ISSUE THREAD

**Issue by Srikanth1022v** [xgeek-net/salesforce-devtools#25]
Query results are not Exporting

**Comment by xgeek-net** [comment]
Hi, @Srikanth1022v , can you share more detail? I can do nothing if that issue can't be reproducible.

**Comment by TheAmigo** [comment]
I have the same problem.  I wrote this query:

`select assignee.name, assignee.username, assignee.email, permissionset.name from permissionsetassignment where permissionset.name like 'SOR%'`

When I click export, it says "Total Rows : 308", the Export button grays out, and the pinwheel on it spins (for minutes).  No download starts. :(

**Comment by xgeek-net** [comment]
Hi, @TheAmigo , thank you for your information. This issue is fixed at latest version(v3.3.1), you can use it to download now.
Feel free to reopen this issue if you have any question.
