### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bentziC** [xgeek-net/salesforce-devtools#28]
It stoped working:
![image](https://user-images.githubusercontent.com/53484116/62138949-30f90780-b2f1-11e9-94af-cfd4fde17485.png)

**Comment by lexluthor0304** [comment]
> It stoped working:
> ![image](https://user-images.githubusercontent.com/53484116/62138949-30f90780-b2f1-11e9-94af-cfd4fde17485.png)

I have the same problem as your had

**Comment by dawn8898** [comment]
Can it be reproduced if you reopen DevTools? And which UI are you using, Classic or Lightning?

**Comment by satyaranjamohanty** [comment]
I have same issue its not working for me in QA and Prod instance but its working in DEV org in classic.

please suggest me any thing i need to enable in my org.

**Comment by xgeek-net** [comment]
@lexluthor0304 @satyaranjamohanty @bentziC 
Hi, guys, this issue was fixed in latest version (v3.7.0), thank you for your issue report.
Please feel free to reopen this if it's still not working for you.
