### ISSUE TITLE
Use .xlsx for exporting definitions

### ISSUE THREAD

**Issue by JeroenSfdc** [xgeek-net/salesforce-devtools#3]
Change from .xls to .xlsx

**Comment by xgeek-net** [comment]
@JeroenSfdc Why?

**Comment by JeroenSfdc** [comment]
@xgeek-net well, because it prevents the message upon opening. I don't think lot op people are still using obsolete office (or alternatives) which cannot handle .xlsx, hence don't give you the popup upon opening the exported data.

**Comment by xgeek-net** [comment]
@JeroenSfdc Okay, will put it in its roadmap. Thanks for your feedback.

**Comment by xgeek-net** [comment]
Hi, @JeroenSfdc , This issue is fixed in latest version (v3.1.0), just FYI.

Regards,
Lin
