### ISSUE TITLE
It just spins

### ISSUE THREAD

**Issue by dlynch0414** [xgeek-net/salesforce-devtools#32]
I click the Active button to use with Lightning and it just spins. Not sure if I'm doing something wrong. Please help!

**Comment by kobyleIL** [comment]
Same behavior in classic for me

**Comment by xgeek-net** [comment]
Any js error occurred on Chrome Console?
Active button on Lightning may not work on Multiple chrome window so close all windows and try again.

**Comment by nicktart24** [comment]
I am getting the same behavior.

from dev tools.

Request URL: https://company.my.salesforce.com/services/data/v42.0/tooling/query?q=SELECT%20Id%2C%20DeveloperName%20FROM%20CustomObject
Request Method: GET
Status Code: 400 Bad Request
Remote Address: 104.129.204.41:80
Referrer Policy: no-referrer-when-downgrade

**Comment by xgeek-net** [comment]
@dlynch0414 @nicktart24 @kobyleIL 
Hi, guys, this issue was fixed in latest version (v3.7.0), thank you for your issue report.
Please feel free to reopen this if it's still not working for you.
