### ISSUE TITLE
一个Object有复数个PageLayout，当出力PageLayout的时候出现下面的Error

### ISSUE THREAD

**Issue by zhenli1026** [xgeek-net/salesforce-devtools#37]
![image](https://user-images.githubusercontent.com/63047672/78239661-f4814980-7518-11ea-8a5e-766c1ff1b097.png)

**Comment by xgeek-net** [comment]
@zhenli1026 
应该是认证发生问题，可以尝试下清空缓存后再打开sf环境重试看看

**Comment by xgeek-net** [comment]
@zhenli1026 Fixed in the latest version (v3.7.1).
