### ISSUE TITLE
Not Working : Keeps loading

### ISSUE THREAD

**Issue by harshal-gajare** [xgeek-net/salesforce-devtools#39]
![image](https://user-images.githubusercontent.com/5017173/79752354-2ef13180-82e2-11ea-8fbd-1f3a74725383.png)

When trying to access Dev Tools on Classic for Salesforce it keeps loading in chrome. 
![image](https://user-images.githubusercontent.com/5017173/79752230-f6e9ee80-82e1-11ea-85bd-589f8edff3c9.png)

Error : 

app.min.js:7 Uncaught TypeError: Cannot read property 'id' of undefined
    at app.min.js:7
    at app.min.js:8
    at u.run (app.min.js:12)
    at l (app.min.js:12)

![image](https://user-images.githubusercontent.com/5017173/79752261-0406dd80-82e2-11ea-9279-95cc1da432ac.png)

Dev console also shows warnings. 

![image](https://user-images.githubusercontent.com/5017173/79753103-601e3180-82e3-11ea-984a-aba70114fd9b.png)

**Comment by xgeek-net** [comment]
Hi, @harshal-gajare 
This issue was fixed in latest version (v3.7.0), thank you for your issue report.
Please feel free to reopen this if it's still not working for you.
