### ISSUE TITLE
chrom extension frozen

### ISSUE THREAD

**Issue by IraSfx** [xgeek-net/salesforce-devtools#40]
Hi, 

I have the app extension add to my chrome, but the screen is stuck in the initial stage 
![Screen Shot 2020-05-06 at 11 42 58](https://user-images.githubusercontent.com/64167496/81178193-84029800-8fb0-11ea-8ad2-d35b8bd385f0.png)

It's frozen on the same screen for lightning and classic and does not allow me to move forward and created an ERD

**Comment by xgeek-net** [comment]
Hi, @IraSfx 
This issue was fixed in latest version (v3.7.0), thank you for your issue report.
Please feel free to reopen this if it's still not working for you.
