### ISSUE TITLE
Extension does not work

### ISSUE THREAD

**Issue by NguyenTatThao** [xgeek-net/salesforce-devtools#45]
Everytime when i open salesforce dev tools extension in google chrome, it says "Seems you are opening this app on a non-Classic page, if you insist, click below button to active, then pray... just kidding. ：）" (picture below)
I've clicked [ACTIVE] button already, but it still doesn't work
I'm newbie, somebody please help!
https://prnt.sc/ty43j3

**Comment by xgeek-net** [comment]
Hi, @NguyenTatThao 
Can you logout your Salesforce account, clear Chrome cache and try it again? if it still doesn't work, please share more detail to help me to reproduce that issue.

**Comment by xgeek-net** [comment]
Hi, @NguyenTatThao 
This issue was fixed in latest version (v3.7.0), thank you for your issue report.
Please feel free to reopen this if it's still not working for you.
