### ISSUE TITLE
No source code / Issue Tracking only.

### ISSUE THREAD

**Issue by enkodellc** [xgeek-net/salesforce-devtools#48]
This looks like a great extension for Salesforce but my company requires a high level of security so I cannot install it without seeing the source code. I understand why you wouldn't make this open source but I also think you should make that very prominent in your Readme.. as in the very first paragraph. It appears you are only using Github to track issues / requests.  Have you every considered open-sourcing this or at least sharing it for a fee. I despise Salesforce "developer console" as it should have several of the features your extension has.

**Comment by xgeek-net** [comment]
Hi @enkodellc 
Thank you for liking my "Salesforce DevTools", as I known many companies has high level of security that forbid to install Chrome Extension on employee's PC, but open source does not work anything for clearing that rule.
Some developers work in financial industry had same issue and asked me to send them crx file,I'm happy to share it if that works for you.

**Comment by enkodellc** [comment]
Hi @xgeek-net   Thank so much for the response and the offer for the crx file. I was able to get that myself and review it a bit.  I would politely disagree with you. Open-source will allow other developers to view the code and see if malicious code was leaking data where it shouldn't go. I am new to Salesforce so I really wanted to use your extension but I there are a few items that are still unclear.   
- Why do you need to log into OAuth through JSForce? Do you have custom code within salesforce to run your extension? Could this be modifed to log into you own custom Salesforce App so that it would be more secure?
- What data are you accessing from each person? It appears that the OAuth agreement you would have access to it all which is concerning and why I could not personally agree to use the extension.

Maybe I am being paranoid but there are too many ways to steal information and I don't want to be a statistic :)

**Comment by xgeek-net** [comment]
Hi, @enkodellc  Thank you for your feedback. DevTools dose not save/leak any your Salesforce data on external service and if you still worry about that you can try it on a Developer Edition, monitor the all network requests with Chrome DevTools (Network Tab).
To answer your questions, JSForce is just an Open Source library to make my development more easier and faster, I don't think there has someone to write all API request code from scratch.
And the below feature needs OAuth agreement to access your Salesforce data, again, that does not mean it will leak your data.
https://github.com/xgeek-net/salesforce-devtools#5-query-editor

Feel free to reopen this issue if you have any other questions.
