### ISSUE TITLE
Object Not Detected in Classic Page Layout with Visualforce Pages Embedded

### ISSUE THREAD

**Issue by Coogie7** [xgeek-net/salesforce-devtools#5]
I have Lightning enabled, but am in Classic mode. I have a Contact page layout with Visualforce pages in the page layout. The extension doesn't detect the object and says it is a non-Classic page, but it is not.

This behavior in Salesforce might be a clue as to why the extension doesn't work:
- This type of page layout doesn't have the "Edit Layout" when viewing a record. I beleive this is expected behavior in Salesforce when you have Visualforce pages embedded in the page layout. Other objects without Visualforce pages embedded do show the "Edit Layout" button.

**Comment by xgeek-net** [comment]
Hi, @Coogie7 

Thank you for your feedback. 
Salesforce DevTools doesn't support Visualforce pages because vf page works on other instances.
