### ISSUE TITLE
Export Object Definition (Full): Doesn't export the Description field

### ISSUE THREAD

**Issue by gpattersonm** [xgeek-net/salesforce-devtools#56]
I have been exporting the `Work Order` Object Definition (FULL) and I am noticing that the Description field is not exported. Help Text is provided but I would like to have Description as well. Is it possible to add this?

**Comment by alejandro-martinez-hernandez** [comment]
It would great if the Description field would be in the file exported.

**Comment by xgeek-net** [comment]
@gpattersonm @alejandro-martinez-hernandez 
Hi there, this request is fixed in the latest version (v.3.10.0).
