### ISSUE TITLE
无法在SF中看到API的详细

### ISSUE THREAD

**Issue by Merrick-Zhang** [xgeek-net/salesforce-devtools#6]
![image](https://user-images.githubusercontent.com/9333902/45378913-b1f7d380-b639-11e8-9efe-b9b9b48af266.png)
如上图所示，插件始终loading状态

**Comment by xgeek-net** [comment]
Hi, @Merrick-Zhang 
Thanks for your feedback.

请提供以下信息帮助我们进行问题判定：
１．DevTools是否可以在整个组织中使用（如无法使用请报告你的instance地址，是否classic或lighting）
２．是否可以在其他object详细页面上使用
３．请列举无法使用的object页面信息（Object API名，详细页面的URL，使用者是否拥有管理员权限）

**Comment by Merrick-Zhang** [comment]
Hi　@xgeek-net 
sorry about reply late.
1. DevTools无论classic或lighting都无法显示。
2. Object详细页面无法使用，但是可以看到页面
![image](https://user-images.githubusercontent.com/9333902/45733554-245d4a80-bc1c-11e8-95de-9b802a9e1413.png)
3. 使用者有管理员权限，由于界面无法打开，所以无法查看包括线索，商机，合同等页面的所有相关API信息

**Comment by xgeek-net** [comment]
Hi, @Merrick-Zhang 
>如上图所示，插件始终loading状态
>2. Object详细页面无法使用，但是可以看到页面

原先是一直loading的状态，现在可以打开search窗口了，可以这么理解？
另外你所打开的Object详细页面URL是什么？

**Comment by Merrick-Zhang** [comment]
@xgeek-net  hi  search窗口在home页面是一直可以看到的，
在其他页面一直都是loading状态。
Object详细页面URL：
https://ptmind.my.salesforce.com/xxxxxxxxx → 这部分是商机ID

下面是控制台报的错
![image](https://user-images.githubusercontent.com/9333902/48322082-113d8880-e669-11e8-8040-5b5b59bfa09f.png)

**Comment by xgeek-net** [comment]
@Merrick-Zhang , 这个问题应该已经在最近的几个更新版本中得以解决了，如果还有其他问题，请随时重开这个issue。
