### ISSUE TITLE
Data/Metadata is from a different org

### ISSUE THREAD

**Issue by CarolynMinn** [xgeek-net/salesforce-devtools#70]
When using Organizer to create a query, I have found that the objects and records displayed are not from the instance I am working in. The most recent time, the instance whose data was being displayed was from an org I was not even logged into. Reloading metadata did not resolve the issue.

**Comment by S4m43L10** [comment]
Same here

**Comment by xgeek-net** [comment]
This issue is fixed in the latest version (v.3.10.0).
