### ISSUE TITLE
Can't export more than 45 objects

### ISSUE THREAD

**Issue by lexluthor0304** [xgeek-net/salesforce-devtools#78]
Error when trying to export more than 45 objects
![soucecode](https://user-images.githubusercontent.com/15118480/190092478-194454af-b42c-4e15-8de6-0b8ce4b8fd45.png)

**Comment by xgeek-net** [comment]
@lexluthor0304 
Will fix it.

**Comment by xgeek-net** [comment]
@lexluthor0304 
45 limit is need base on UI/UX reasons, try to export multiple times if you want more than 45 objects.
