### ISSUE TITLE
cannot use

### ISSUE THREAD

**Issue by LiNengYu** [xgeek-net/salesforce-devtools#8]
![capture](https://user-images.githubusercontent.com/21236795/47344348-d506b000-d6da-11e8-8b57-0eaa159d6379.PNG)
在Apex Debug Log Detail中，点击Active Debug Log Viewer没反应。

**Comment by xgeek-net** [comment]
@LiNengYu Debug Log Viewer feature is disabled temporarily (for supporting Lightning) in v3.0.0, and it will come back in next version.
Thanks for your feedback.

**Comment by LiNengYu** [comment]
> @LiNengYu Debug Log Viewer feature is disabled temporarily (for supporting Lightning) in v3.0.0, and it will come back in next version.
> Thanks for your feedback.

thx, great tool.

**Comment by xgeek-net** [comment]
Hi, @LiNengYu 
This issue is fixed at latest version (v3.2.0).
