### ISSUE TITLE
I couldn't execute Field Clone function

### ISSUE THREAD

**Issue by sotacckuer** [xgeek-net/salesforce-devtools#87]
![スクリーンショット 2023-05-24 155611](https://github.com/xgeek-net/salesforce-devtools/assets/65263782/f80b4ea7-2fe7-4f2a-b2cc-d4a48d7e47ae)

The button to clone field does not display.
Other functions are available.

**Comment by xgeek-net** [comment]
@sotacckuer 
It is available on both Classic and Lightning now, reference the following page to this feature.
https://www.xgeek.net/salesforce-devtools/salesforce-devtools-release-notes-version-3-10-0-mass-edit-custom-fields-on-lightning/

**Comment by sotacckuer** [comment]
@xgeek-net 
The operation procedure had been changed.
Thank you for letting me know.
