### ISSUE TITLE
Enhancement to object API reference export

### ISSUE THREAD

**Issue by jbuckfs** [xgeek-net/salesforce-devtools#9]
This tool does so much. I really love it. I wanted to ask if on the object API reference export, could you also bring in the description and help text for each field? We put notes in these areas that would be helpful to have in our documentation, as well.

**Comment by xgeek-net** [comment]
Hi, @jbuckfs , Thank you for your feedback. Your enhancement sounds good, will pull this in its roadmap.

**Comment by xgeek-net** [comment]
Hi, @jbuckfs 
This issue is fixed at latest version (v3.2.0), please upgrade it and try again.
BTW, help text is added but description can't be exported.

**Comment by jbuckfs** [comment]
Awesome. Thank you. This is great. Description seems to be a problem for every tool I have tried but I think we can make this work with help text.

Thank you again!

Jamie E. Buck-Tomek | Senior Salesforce Administrator | Foundation Source
Phone: 203-319-3765 | eFax: 203-292-4165 | jbuck@foundationsource.com<mailto:jbuck@foundationsource.com>
www.foundationsource.com<http://www.foundationsource.com>

Foundation Source
55 Walls Drive, 3rd Floor, Fairfield CT 06824

[cid:image07f2cd.JPG@5bf93a11.4ca8f19f]<http://www.facebook.com/Foundation.Source>      [cid:imaged831cb.JPG@24bbad5d.48bdd07d] <http://twitter.com/foundationsrc>      [cid:image8e5067.JPG@c77ad1d3.42bd7389] <http://www.linkedin.com/company/28909?trk=s>


The finest compliment we can receive is an introduction to friends, family, and colleagues from an appreciative client.



________________________________
Foundation Source is the nation's leading provider of support services for private foundations. The contents of this email are provided for informational purposes only and should not be construed as tax, legal or financial advice.
